/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dragonshout;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 * DragonShout --- Create and Display a Dragon Shout
 * @author Ashwika Katiyar
 */
public class DragonShout extends javax.swing.JFrame {

    private String fileName;
    
    /**
     * Creates new form DragonShout
     */
    public DragonShout(String file) {
        initComponents();
        ImageIcon bg = new ImageIcon("shout.jpg");
        background.setIcon(bg);
        this.setSize(bg.getIconWidth() + 3, bg.getIconHeight() + 40);
        fileName = file;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JButton();
        firstLabel = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();
        thirdLabel = new javax.swing.JLabel();
        word1 = new javax.swing.JTextField();
        word2 = new javax.swing.JTextField();
        word3 = new javax.swing.JTextField();
        createShout = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        shout = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        home.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(800, 80, 80, 30);

        firstLabel.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        firstLabel.setForeground(new java.awt.Color(238, 208, 179));
        firstLabel.setText("Enter 1st Word:");
        getContentPane().add(firstLabel);
        firstLabel.setBounds(20, 20, 120, 30);

        secondLabel.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        secondLabel.setForeground(new java.awt.Color(238, 208, 179));
        secondLabel.setText("Enter 3rd Word:");
        getContentPane().add(secondLabel);
        secondLabel.setBounds(610, 20, 150, 30);

        thirdLabel.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        thirdLabel.setForeground(new java.awt.Color(238, 208, 179));
        thirdLabel.setText("Enter 2nd Word:");
        getContentPane().add(thirdLabel);
        thirdLabel.setBounds(310, 20, 160, 30);
        getContentPane().add(word1);
        word1.setBounds(140, 20, 150, 30);
        getContentPane().add(word2);
        word2.setBounds(440, 20, 150, 30);
        getContentPane().add(word3);
        word3.setBounds(740, 20, 150, 30);

        createShout.setFont(new java.awt.Font("Goudy Stout", 0, 12)); // NOI18N
        createShout.setForeground(new java.awt.Color(62, 67, 69));
        createShout.setText("Shout!");
        createShout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createShoutActionPerformed(evt);
            }
        });
        getContentPane().add(createShout);
        createShout.setBounds(360, 80, 210, 30);

        clear.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(30, 80, 80, 30);

        shout.setFont(new java.awt.Font("Elephant", 1, 60)); // NOI18N
        shout.setForeground(new java.awt.Color(62, 67, 69));
        shout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(shout);
        shout.setBounds(10, 410, 880, 90);
        getContentPane().add(background);
        background.setBounds(0, 0, 910, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sends user to the Home selection screen
     * @param evt 
     */
    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Home home = new Home(fileName);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    /**
     * Creates and displays Dragon shout based on English words entered
     * Only considers the first word entered in each field
     * @param evt 
     */
    private void createShoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createShoutActionPerformed
        try {
            DragonTranslator translator = new DragonTranslator(fileName);
            String first = word1.getText();
            if(first.contains(" ")){
                first = first.substring(0, first.indexOf(" "));
            }
            String second = word2.getText();
            if(second.contains(" ")){
                second = second.substring(0, second.indexOf(" "));
            }
            String third = word3.getText();
            if(third.contains(" ")){
                third = third.substring(0, third.indexOf(" "));
            }
            String text = translator.translate(first) + " " + translator.translate(second) + " " + translator.translate(third) + "!";
            shout.setText(text);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DragonShout.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_createShoutActionPerformed

    /**
     * Clears the word fields
     * @param evt 
     */
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        word1.setText("");
        word2.setText("");
        word3.setText("");
    }//GEN-LAST:event_clearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton clear;
    private javax.swing.JButton createShout;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JButton home;
    private javax.swing.JLabel secondLabel;
    private javax.swing.JLabel shout;
    private javax.swing.JLabel thirdLabel;
    private javax.swing.JTextField word1;
    private javax.swing.JTextField word2;
    private javax.swing.JTextField word3;
    // End of variables declaration//GEN-END:variables
}
