/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dragonshout;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 * Dragon Word --- add a Dragon word
 * @author Ashwika Katiyar
 */
public class DragonWord extends javax.swing.JFrame {

    private String fileName;
    /**
     * Creates new form DragonWord
     */
    public DragonWord(String file) {
        initComponents();
        ImageIcon bg = new ImageIcon("word.jpg");
        background.setIcon(bg);
        this.setSize(bg.getIconWidth() + 3, bg.getIconHeight() + 40);
        fileName = file;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JButton();
        english = new javax.swing.JTextField();
        dragon = new javax.swing.JTextField();
        dragonLabel = new javax.swing.JLabel();
        englishLabel = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        addStatus = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        home.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(780, 30, 80, 30);
        getContentPane().add(english);
        english.setBounds(40, 380, 400, 50);
        getContentPane().add(dragon);
        dragon.setBounds(480, 380, 400, 50);

        dragonLabel.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        dragonLabel.setForeground(new java.awt.Color(238, 208, 179));
        dragonLabel.setText("Enter Dragon Translation:");
        getContentPane().add(dragonLabel);
        dragonLabel.setBounds(490, 340, 240, 20);

        englishLabel.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        englishLabel.setText("Enter English Word:");
        getContentPane().add(englishLabel);
        englishLabel.setBounds(50, 340, 230, 20);

        add.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        add.setText("Create Translation");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(250, 460, 200, 30);

        clear.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(470, 460, 110, 30);

        addStatus.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        addStatus.setForeground(new java.awt.Color(255, 255, 255));
        addStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(addStatus);
        addStatus.setBounds(120, 20, 670, 50);
        getContentPane().add(background);
        background.setBounds(-10, 0, 920, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sends user to the Home selection screen
     * @param evt 
     */
    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Home home = new Home(fileName);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    /**
     * Adds a new Dragon Word and translation based on words entered if allowed
     * @param evt 
     */
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        try {
            DragonTranslator translator = new DragonTranslator(fileName);
            boolean wasAdded = translator.add(dragon.getText(), english.getText());
            if(wasAdded){
                addStatus.setText("Success - word added!");
            }
            else{
                addStatus.setText("Failed - word could not be added :(");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DragonWord.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DragonWord.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_addActionPerformed

    /**
     * Clears the word fields
     * @param evt 
     */
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        english.setText("");
        dragon.setText("");
        addStatus.setText("");
    }//GEN-LAST:event_clearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel addStatus;
    private javax.swing.JLabel background;
    private javax.swing.JButton clear;
    private javax.swing.JTextField dragon;
    private javax.swing.JLabel dragonLabel;
    private javax.swing.JTextField english;
    private javax.swing.JLabel englishLabel;
    private javax.swing.JButton home;
    // End of variables declaration//GEN-END:variables
}
