/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dragonshout;

import javax.swing.*;

/**
 * Home --- Home Selection Screen
 * @author Ashwika Katiyar
 */
public class Home extends javax.swing.JFrame {

    private String fileName;
    /**
     * Creates new form Home
     */
    public Home(String file) {
        initComponents();
        ImageIcon bg = new ImageIcon("home.jpg");
        background.setIcon(bg);
        this.setSize(bg.getIconWidth() + 3, bg.getIconHeight() + 40);
        fileName = file;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dragonWord = new javax.swing.JButton();
        dragonShout = new javax.swing.JButton();
        translator = new javax.swing.JLabel();
        dragon = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        dragonWord.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        dragonWord.setForeground(new java.awt.Color(0, 51, 51));
        dragonWord.setText("Add a Dragon Word");
        dragonWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dragonWordActionPerformed(evt);
            }
        });
        getContentPane().add(dragonWord);
        dragonWord.setBounds(20, 160, 270, 60);

        dragonShout.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        dragonShout.setForeground(new java.awt.Color(0, 51, 51));
        dragonShout.setText("Create a Dragon Shout");
        dragonShout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dragonShoutActionPerformed(evt);
            }
        });
        getContentPane().add(dragonShout);
        dragonShout.setBounds(20, 60, 270, 60);

        translator.setFont(new java.awt.Font("Goudy Stout", 1, 36)); // NOI18N
        translator.setForeground(new java.awt.Color(2, 60, 76));
        translator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        translator.setText("Translator");
        getContentPane().add(translator);
        translator.setBounds(320, 100, 540, 130);

        dragon.setFont(new java.awt.Font("Goudy Stout", 1, 36)); // NOI18N
        dragon.setForeground(new java.awt.Color(2, 60, 76));
        dragon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dragon.setText("Dragon ");
        getContentPane().add(dragon);
        dragon.setBounds(320, 30, 540, 130);

        background.setMaximumSize(new java.awt.Dimension(910, 513));
        background.setMinimumSize(new java.awt.Dimension(910, 513));
        background.setPreferredSize(new java.awt.Dimension(910, 513));
        getContentPane().add(background);
        background.setBounds(-10, -10, 940, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sends user to the Dragon Shout page
     * @param evt 
     */
    private void dragonShoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dragonShoutActionPerformed
        DragonShout shout = new DragonShout(fileName);
        shout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dragonShoutActionPerformed

    /**
     * Sends user to page to add a Dragon word 
     * @param evt 
     */
    private void dragonWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dragonWordActionPerformed
        DragonWord word = new DragonWord(fileName);
        word.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dragonWordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel dragon;
    private javax.swing.JButton dragonShout;
    private javax.swing.JButton dragonWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel translator;
    // End of variables declaration//GEN-END:variables
}
